const axios = require('axios');

class AvatarService {
  constructor() {
    this.enabled = process.env.AVATAR_ENABLED === 'true';
    this.provider = process.env.AVATAR_PROVIDER || 'heygen';
    this.videoStreaming = process.env.AVATAR_VIDEO_STREAMING === 'true';
    this.quality = process.env.AVATAR_QUALITY || 'high';
    this.fps = parseInt(process.env.AVATAR_FPS) || 30;
    this.rtcUid = process.env.AVATAR_RTC_UID || '9999';
    
    // Initialize provider-specific configurations
    this.initializeProviders();
  }

  // Initialize all avatar providers
  initializeProviders() {
    this.providers = {
      heygen: {
        apiKey: process.env.HEYGEN_API_KEY,
        avatarId: process.env.HEYGEN_AVATAR_ID,
        model: process.env.HEYGEN_MODEL || 'heygen-1.0',
        voiceId: process.env.HEYGEN_VOICE_ID
      },
      akool: {
        apiKey: process.env.AKOOL_API_KEY,
        avatarId: process.env.AKOOL_AVATAR_ID,
        model: process.env.AKOOL_MODEL || 'akool-1.0',
        voiceId: process.env.AKOOL_VOICE_ID
      }
    };
  }

  // Check if provider is configured
  isProviderConfigured(provider) {
    const config = this.providers[provider];
    return !!(config?.apiKey && config?.avatarId);
  }

  // Validate avatar configuration
  validateConfig() {
    if (!this.enabled) {
      return { valid: false, reason: 'AI Avatar is disabled' };
    }

    if (!this.isProviderConfigured(this.provider)) {
      return { valid: false, reason: `${this.provider} avatar is not properly configured` };
    }

    return { valid: true };
  }

  // Get avatar configuration for agent
  getAvatarConfig() {
    const validation = this.validateConfig();
    if (!validation.valid) {
      return null;
    }

    const config = this.providers[this.provider];
    
    const baseConfig = {
      enable_avatar: true,
      avatar_vendor: this.provider,
      avatar_api_key: config.apiKey,
      avatar_id: config.avatarId,
      avatar_rtc_uid: this.rtcUid,
      avatar_quality: this.quality,
      avatar_fps: this.fps
    };

    // Provider-specific configurations
    if (this.provider === 'heygen') {
      return {
        ...baseConfig,
        avatar_model: config.model,
        avatar_voice_id: config.voiceId,
        avatar_rtc_token: null, // Will be generated by Agora
        disable_idle_timeout: false,
        activity_idle_timeout: 60
      };
    } else if (this.provider === 'akool') {
      return {
        ...baseConfig,
        avatar_model: config.model,
        avatar_voice_id: config.voiceId,
        avatar_rtc_token: null // Will be generated by Agora
      };
    }

    return baseConfig;
  }

  // Generate avatar placeholder SVG
  generatePlaceholderSVG() {
    return `
      <svg width="120" height="120" viewBox="0 0 120 120" xmlns="http://www.w3.org/2000/svg">
        <!-- Background circle -->
        <circle cx="60" cy="60" r="50" fill="none" stroke="#00ffff" stroke-width="2" opacity="0.3"/>
        <!-- AI Icon -->
        <g transform="translate(60, 45)">
          <!-- Brain/Neural network representation -->
          <circle cx="0" cy="0" r="8" fill="none" stroke="#00ffff" stroke-width="1.5"/>
          <circle cx="-12" cy="-8" r="4" fill="none" stroke="#00ffff" stroke-width="1.5"/>
          <circle cx="12" cy="-8" r="4" fill="none" stroke="#00ffff" stroke-width="1.5"/>
          <circle cx="-8" cy="12" r="4" fill="none" stroke="#00ffff" stroke-width="1.5"/>
          <circle cx="8" cy="12" r="4" fill="none" stroke="#00ffff" stroke-width="1.5"/>
          <!-- Connection lines -->
          <line x1="-12" y1="-8" x2="0" y2="0" stroke="#00ffff" stroke-width="1" opacity="0.7"/>
          <line x1="12" y1="-8" x2="0" y2="0" stroke="#00ffff" stroke-width="1" opacity="0.7"/>
          <line x1="-8" y1="12" x2="0" y2="0" stroke="#00ffff" stroke-width="1" opacity="0.7"/>
          <line x1="8" y1="12" x2="0" y2="0" stroke="#00ffff" stroke-width="1" opacity="0.7"/>
        </g>
        <!-- Text -->
        <text x="60" y="85" text-anchor="middle" fill="#00ffff" font-family="Arial, sans-serif" font-size="12" font-weight="bold">AI AVATAR</text>
      </svg>
    `;
  }

  // Get avatar status
  getAvatarStatus() {
    const validation = this.validateConfig();
    const currentProvider = this.providers[this.provider];
    return {
      enabled: this.enabled,
      provider: this.provider,
      configured: this.isProviderConfigured(this.provider),
      valid: validation.valid,
      reason: validation.reason,
      videoStreaming: this.videoStreaming,
      quality: this.quality,
      fps: this.fps,
      providerConfig: currentProvider,
      placeholder: this.generatePlaceholderSVG()
    };
  }

  // Create avatar stream
  async createAvatarStream(text, options = {}) {
    const provider = options.provider || this.provider;
    const config = this.providers[provider];

    if (!this.enabled || !this.isProviderConfigured(provider)) {
      throw new Error(`${provider} avatar service not properly configured`);
    }

    try {
      switch (provider) {
        case 'heygen':
          return await this.createHeyGenAvatar(text, config);
        case 'akool':
          return await this.createAkoolAvatar(text, config);
        default:
          throw new Error(`Unsupported avatar provider: ${provider}`);
      }
    } catch (error) {
      console.error('Error creating avatar stream:', error);
      throw error;
    }
  }

  // Create HeyGen avatar
  async createHeyGenAvatar(text, config) {
    try {
      const url = 'https://api.heygen.com/v1/video.generate';
      
      const response = await axios.post(url, {
        video_inputs: [{
          character: {
            type: 'avatar',
            avatar_id: config.avatarId
          },
          voice: {
            type: 'text',
            input_text: text,
            voice_id: config.voiceId
          }
        }],
        test: false,
        aspect_ratio: '16:9',
        quality: this.quality,
        fps: this.fps
      }, {
        headers: {
          'X-Api-Key': config.apiKey,
          'Content-Type': 'application/json'
        }
      });

      return {
        videoId: response.data.data.video_id,
        status: 'processing',
        provider: 'heygen',
        quality: this.quality,
        fps: this.fps
      };
    } catch (error) {
      console.error('Error creating HeyGen avatar:', error.response?.data || error.message);
      throw new Error('Failed to create HeyGen avatar');
    }
  }

  // Create Akool avatar
  async createAkoolAvatar(text, config) {
    try {
      const url = 'https://api.akool.com/v1/avatar/generate';
      
      const response = await axios.post(url, {
        avatar_id: config.avatarId,
        text: text,
        voice_id: config.voiceId,
        model: config.model,
        quality: this.quality,
        fps: this.fps
      }, {
        headers: {
          'Authorization': `Bearer ${config.apiKey}`,
          'Content-Type': 'application/json'
        }
      });

      return {
        videoId: response.data.video_id,
        status: 'processing',
        provider: 'akool',
        quality: this.quality,
        fps: this.fps
      };
    } catch (error) {
      console.error('Error creating Akool avatar:', error.response?.data || error.message);
      throw new Error('Failed to create Akool avatar');
    }
  }

  // Get avatar video status
  async getAvatarVideoStatus(videoId, provider = null) {
    const currentProvider = provider || this.provider;

    try {
      switch (currentProvider) {
        case 'heygen':
          return await this.getHeyGenStatus(videoId);
        case 'akool':
          return await this.getAkoolStatus(videoId);
        default:
          throw new Error(`Unsupported avatar provider: ${currentProvider}`);
      }
    } catch (error) {
      console.error('Error getting avatar status:', error);
      throw error;
    }
  }

  // Get HeyGen video status
  async getHeyGenStatus(videoId) {
    const config = this.providers.heygen;
    
    try {
      const url = `https://api.heygen.com/v1/video.get?video_id=${videoId}`;
      
      const response = await axios.get(url, {
        headers: {
          'X-Api-Key': config.apiKey
        }
      });

      return {
        videoId: videoId,
        status: response.data.data.status,
        videoUrl: response.data.data.video_url,
        provider: 'heygen',
        quality: this.quality,
        fps: this.fps
      };
    } catch (error) {
      console.error('Error getting HeyGen status:', error.response?.data || error.message);
      throw new Error('Failed to get HeyGen video status');
    }
  }

  // Get Akool video status
  async getAkoolStatus(videoId) {
    const config = this.providers.akool;
    
    try {
      const url = `https://api.akool.com/v1/avatar/status/${videoId}`;
      
      const response = await axios.get(url, {
        headers: {
          'Authorization': `Bearer ${config.apiKey}`
        }
      });

      return {
        videoId: videoId,
        status: response.data.status,
        videoUrl: response.data.video_url,
        provider: 'akool',
        quality: this.quality,
        fps: this.fps
      };
    } catch (error) {
      console.error('Error getting Akool status:', error.response?.data || error.message);
      throw new Error('Failed to get Akool video status');
    }
  }

  // Update avatar configuration
  updateAvatarConfig(config) {
    if (config.enable_avatar !== undefined) {
      this.enabled = config.enable_avatar;
    }
    if (config.avatar_vendor) {
      this.provider = config.avatar_vendor;
    }
    if (config.avatar_api_key) {
      // Update the appropriate provider's API key
      if (this.providers[this.provider]) {
        this.providers[this.provider].apiKey = config.avatar_api_key;
      }
    }
    if (config.avatar_id) {
      // Update the appropriate provider's avatar ID
      if (this.providers[this.provider]) {
        this.providers[this.provider].avatarId = config.avatar_id;
      }
    }
    if (config.avatar_rtc_uid) {
      this.rtcUid = config.avatar_rtc_uid;
    }

    return this.getAvatarConfig();
  }
}

module.exports = new AvatarService(); 